import axios from "axios";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { useEffect, useState } from "react";
import { FcSearch } from "react-icons/fc";
import MiniCompoent from "./components/miniCompoent";
import urlImg from "../public/logo.png";
import Image from "next/image";
import dayjs from "dayjs";
import AutoCompleteComponent from "./components/AutoComplete";
import { CircularProgress } from "@mui/material";
import Top50Component from "./components/Top50Component";
import News from "./components/News";
function Detail() {
  const router = useRouter();
  const [infor, setInfor] = useState();
  const [loading, setLoading] = useState(true);
  const {
    query: { id },
  } = router;
  useEffect(() => {
    setLoading(true);
    if (id) {
      axios
        .get("https://api.call-spam-blocker.xyz/phone-numbers/detail/" + id, {
          headers: { authorization: "spambl0ckerAuthorization2k1rbyp0wer" },
        })
        .then((data) => {
          setInfor(data.data.result);
          setLoading(false);
        });
    }
  }, [id]);
  return (
    <>
      <Head>
        <title>CheckCallSpammer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={"../public/logo"} />
      </Head>
      <main className="relative">
        <div className="w-100 pl-[10px] pt-[2px] flex flex-row justify-between h-[62px] bg-[#4BE1BA]">
          <Image
            alt="logo"
            width={60}
            height={40}
            onClick={() => {
              router.push({
                pathname: "/",
              });
            }}
            src={urlImg}
            className="my-auto"
          />
          <div className="flex flex-row border-5 border-black rounded-[6px] my-auto  w-[500px] ">
            <AutoCompleteComponent />
          </div>
          <p className="text-[#4BE1BA]">adcd</p>
        </div>
        <p className=" font-bold md:text-[50px] text-[25px] text-center text-[#221f49] ">
          About this number
        </p>
        {loading === false ? (
          <div>
            <div className="w-[98%] my-[15px] rounded-[16px]  bg-[#bfc3c9]  mx-auto">
              <MiniCompoent
                types="line"
                headerLine="Number Phone:"
                contents={infor.phoneNumber}
              />

              <MiniCompoent
                types="line"
                headerLine="Status:"
                contents={infor.status}
              />
              <MiniCompoent
                types="line"
                headerLine="Number Report:"
                contents={infor.reportList.length + " report"}
              />
            </div>
            <div className="w-[98%]  pl-[5px] flex flex-row flex-wrap justify-center   ">
              <MiniCompoent
                types="noti"
                headerLine="Provider:"
                contents={infor.name}
              />
              <MiniCompoent
                types="noti"
                headerLine="Country"
                contents={"Viet Nam"}
              />
              <MiniCompoent
                types="noti"
                headerLine="Country Code:"
                contents={infor.region.regionCode}
              />
            </div>
            <p className="font-medium md:text-[50px] text-[25px] text-center text-[#221f49]  pt-[25px]">
              Report
            </p>
            <div className="flex flex-row flex-wrap justify-center">
              {infor.reportList.map((value, index) => (
                <MiniCompoent
                  types="comments"
                  number={value.title}
                  hourse={dayjs(value.reportDate).format("DD-MM-YYYY")}
                  comment={value.content}
                  key={index}
                />
              ))}
            </div>
          </div>
        ) : (
          <div className="text-center">
            <CircularProgress />
          </div>
        )}
        <p className="font-medium md:text-[50px] text-[25px] text-center text-[#221f49]  pt-[25px]">
          The suggest phone
        </p>
        <div className="flex flex-row flex-wrap justify-center">
          <Top50Component />
        </div>{" "}
        <p className="font-medium md:text-[50px] text-[25px] text-center text-[#221f49]  pt-[25px]">
          The News
        </p>
        <div className="flex flex-row flex-wrap justify-center">
          <News />
        </div>
      </main>
      <MiniCompoent types="footer" />
    </>
  );
}

export default Detail;
