import axios from "axios";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { useEffect, useState } from "react";
import { FcSearch } from "react-icons/fc";
import MiniCompoent from "../components/miniCompoent";
import urlImg from "../public/logo.png";
import Image from "next/image";
import dayjs from "dayjs";
import AutoCompleteComponent from "../components/AutoComplete";
import { Chip, CircularProgress } from "@mui/material";
import Top50Component from "../components/Top50Component";
import News from "../components/News";
function Detail() {
  const time = new Date();
  const date = time.getDate();
  const month = time.getMonth() + 1;
  const curMonthYear = date + "-" + month + "-" + time.getFullYear();
  const router = useRouter();
  const [infor, setInfor] = useState();
  const [loading, setLoading] = useState(true);
  const {
    query: { id },
  } = router;
  useEffect(() => {
    setLoading(true);
    if (id) {
      axios
        .get("https://api.call-spam-blocker.xyz/phone-numbers/detail/" + id, {
          headers: { authorization: "spambl0ckerAuthorization2k1rbyp0wer" },
        })
        .then((data) => {
          setInfor(data.data.result);
          setLoading(false);
        });
    }
  }, [id]);
  return (
    <>
      <Head>
        <title>Call Spam blocker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href={
            "https://www.callspamblocker.online/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Flogo.272f7cfe.png&w=384&q=75"
          }
        />
      </Head>
      <main className="relative">
        <div className="w-100 md:pl-[10px] pt-[2px] flex flex-row mx-a  justify-between h-[62px] bg-[#4BE1BA]">
          <Image
            alt="logo"
            width={60}
            height={40}
            onClick={() => {
              router.push({
                pathname: "/",
              });
            }}
            src={urlImg}
            className="my-auto md:block hidden cursor-pointer  "
          />

          <div className=" rounded-[6px]  md:w-[500px] w-[300px] mx-auto mt-[1px]">
            <AutoCompleteComponent />
          </div>
        </div>
        <p className=" font-bold md:text-[50px] text-[25px] text-center text-[#221f49] ">
          About this number
        </p>
        {loading === false ? (
          <div>
            <div className="md:w-full w-[80%] mx-auto h-[200x]   p-[15px] mt-[20px] rounded-2xl bg-[#c1c1c1]">
              <p className="md:text-[40px] text-[20px] text-[#696969] font-semibold">
                The phone number is{" "}
                <a className="font-bold text-[#221f49] underline">
                  {infor.phoneNumber}
                </a>
              </p>
              <p className="md:text-[25px] text-[12px]">
                This phone number is provided by{" "}
                <a className="underline font-bold">{infor.name}</a> and is a
                phone number in{" "}
                <a className=" text-[red] font-bold">Viet Nam</a> with the code
                is <Chip label={"+84"} color="info" size="small" />
              </p>
              <p className="text-[20px] ">
                -{" "}
                <a className="font-bold text-[#221f49] underline">
                  {infor.phoneNumber}
                </a>{" "}
                can be a scam if:
              </p>
              <ul className="list-decimal pl-12">
                <li className="text-[20px] ">
                  You are asked to provide personal information or money.
                </li>
                <li className="text-[20px] ">
                  The message instructs you to click on a link or call to another
                  number.
                </li>
                <li className="text-[20px] ">
                  They pretend to be your phone company or bank.
                </li>
                <li className="text-[20px] ">
                  You are being threatened or made to feel scared.
                </li>
                <li className="text-[20px] ">
                  The caller wants to access and control your computer.
                </li>
              </ul>
              <p className="text-[20px] ">- To protect yourself:</p>
              <ul className="list-decimal pl-12">
                <li className="text-[20px] ">
                  Don&apos;t answer if you don&apos;t know who it is.
                </li>
                <li className="text-[20px] ">Do not send any money.</li>
                <li className="text-[20px] ">
                  Never share any personal or banking information about
                  yourself.
                </li>
                <li className="text-[20px] ">
                  If someone claiming to be from an organization, agency, or
                  company, verify the number carefully from the official website
                  of that organization, agency, or company.
                </li>
                <li className="text-[20px] ">Don&apos;t click on any links.</li>
                <li className="text-[20px] ">
                  Never allow a stranger to control your computer.
                </li>
                <li className="text-[20px] ">
                  Block the calls on your mobile phone.
                </li>
              </ul>
              <p className="text-[20px] ">
                - If you are receiving a call from the number 02488899821 that
                is a scam call or if you are regularly harassed by this number,
                you can report this as a scam. Your
                report will help others easily verify suspicious phone numbers.
              </p>
            </div>
            <div className="md:w-full w-[80%] mx-auto h-[200x] flex md:flex-row flex-col p-[15px] md:justify-between mt-[20px] rounded-2xl bg-[#c1c1c1]">
              <MiniCompoent
                types="information"
                header="Today"
                title={
                  infor.searchTracked[infor.searchTracked.length - 1]
                    .numberSearch
                }
                detail={"Searches"}
              />
              <hr className="md:visible" />
              <MiniCompoent
                types="information"
                header="Yesterday"
                title={
                  infor.searchTracked.length > 2
                    ? infor.searchTracked[infor.searchTracked.length - 2]
                        .numberSearch
                    : 0
                }
                detail={"Searches"}
              />
              <hr className="md:visible" />
              <MiniCompoent
                types="information"
                header="Total"
                title={infor.searchTracked.reduce((prev, cur) => {
                  return cur.numberSearch + prev;
                }, 0)}
                detail={"Searches"}
              />
              <hr className="md:visible" />
              <MiniCompoent
                types="information"
                title={
                  <Chip
                    variant="filled"
                    color={
                      infor.status === "unknown"
                        ? "secondary"
                        : infor.status === "spammer"
                        ? "error"
                        : "primary"
                    }
                    size={"50"}
                    className="capitalize "
                    style={{ marginBottom: "auto", marginTop: "auto" }}
                    label={infor.status}
                  />
                }
                color={
                  infor.status === "unknown"
                    ? "#008080"
                    : infor.status === "spammer"
                    ? "red"
                    : "#008080"
                }
                detail={
                  infor.status === "unknown"
                    ? "Safe!"
                    : infor.status === "spammer"
                    ? "Dangerous!"
                    : "Safe!"
                }
                header={"Status"}
              />
              <hr className="md:visible" />
              <MiniCompoent
                types="information"
                header={"Reports"}
                title={infor.reportList.length}
                color="#1e2746"
                colorTitle="white"
                detail={"Times"}
              />
            </div>

            <p className="font-medium md:text-[50px] text-[25px] text-center text-[#221f49]  pt-[25px]">
              Reports
            </p>
            <div className="flex flex-row flex-wrap justify-center">
              {infor.reportList.map((value, index) => (
                <MiniCompoent
                  types="comments"
                  number={value.title}
                  hourse={dayjs(value.reportDate).format("DD-MM-YYYY")}
                  comment={value.content}
                  key={index}
                />
              ))}
            </div>
          </div>
        ) : (
          <div className="text-center">
            <CircularProgress />
          </div>
        )}
        <p className="font-medium md:text-[50px] text-[25px] text-center text-[#221f49]  pt-[25px]">
          Suggest Numbers
        </p>
        <div className="flex flex-row flex-wrap justify-center">
          <Top50Component />
        </div>
        <p className="font-medium md:text-[50px] text-[25px] text-center text-[#221f49]  pt-[25px]">
          News
        </p>
        <div className="flex flex-row flex-wrap justify-center">
          <News />
        </div>
      </main>
      <MiniCompoent types="footer" />
    </>
  );
}

export default Detail;
